[project]
name = "bible-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=24.3.1",
    "pytest>=8.3.3",
    "pytest-mock>=3.14.0",
    "spacy>=3.8.2",
    "bs4>=0.0.2",
    "regex>=2024.11.6",
]
