version: 3

includes:
  occupation::
    taskfile: "./occupation/taskfile.yaml"
    ignore_error: true
    optional: true
    aliases:
      - "occ"
  lifespan::
    taskfile: "./lifespan/taskfile.yaml"
    ignore_error: true
    optional: true
    aliases:
      - "life"

tasks:
  default: task -a

  uv-sync:
    cmds:
      - |
        uv sync
        uv run python3 -m spacy download en_core_web_sm
