version: 3

includes:
  occupation::
    taskfile: "./person_occupation/taskfile.yaml"
    ignore_error: true
    optional: true
    aliases:
      - "pocc"
  lifespan::
    taskfile: "./lifespan/taskfile.yaml"
    ignore_error: true
    optional: true
    aliases:
      - "life"

tasks:
  default: task -a
