version: 3

vars:
  setup_tmp:
    sh: mkdir -p tmp && echo tmp
  out: tmp/out.csv
  show_cnt: 16

tasks:
  default: task -a

  run: task -p generate-json extract
  status:
    silent: true
    cmds:
      - |
        jq '
        {
          total_books: (.nwt | keys | length),
          total_chapters: (.nwt | to_entries | map(.value | keys | length) | add),
          total_verses: (.nwt | to_entries | map(.value | to_entries | map(.value | keys | length) | add) | add)
        }' bible_data.json

      - |
        # verse count
        verses=$(mlr --csv --implicit-csv-header --headerless-csv-output --from bible_data.csv \
          cut -f 1,2 \
          then count)

        # book count
        chapters=$(mlr --csv --implicit-csv-header --headerless-csv-output --from bible_data.csv \
          cut -f 1,2 \
          then uniq -a \
          then count)

        # books count
        books=$(mlr --csv --implicit-csv-header --headerless-csv-output --from bible_data.csv \
          cut -f 1 \
          then uniq -a \
          then count)
        echo "$books,$chapters,$verses" | mlr --d2p --barred cat then label books,chpaters,verses

  convert_2_csv:
    cmds:
      - |
        jq -r '
          .nwt | to_entries[] as $book_entry
          | $book_entry.value | to_entries[] as $chapter_entry
          | $chapter_entry.value | to_entries[] as $verse_entry
          | [$book_entry.key, $chapter_entry.key, $verse_entry.key, $verse_entry.value] | @csv
        ' bible_data.json > bible_data.csv

  generate-json:
    cmds:
      - |
        uv run bible.py --generate

  extract-sample:
    cmds:
      - |
        uv run bible.py \
          --extract \
          --bible-json "bible_data.json" \
          --output-json "bible_entities.json" \
          --output-csv "bible_entities.csv" \
          --books john

  extract:
    cmds:
      - |
        uv run bible.py \
          --extract \
          --bible-json "bible_data.json" \
          --output-json "bible_entities.json" \
          --output-csv "bible_entities.csv"

  summary:
    silent: true
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          count-distinct -f Type \
          then put '
            $Explanation =
              $Type == "PERSON"     ? "Names of individuals" :
              $Type == "DATE"       ? "Explicit or implicit date expressions" :
              $Type == "GPE"        ? "Geopolitical entities (places)" :
              $Type == "ORG"        ? "Organizations or groups" :
              $Type == "OCCUPATION" ? "Roles or professions" :
              $Type == "NORP"       ? "Nationalities, religious or political groups" :
                                      "Other";
          ' \
          then reorder -f Type,count,Explanation

  org:
    silent: true
    cmds:
      - |
        mlr --csv --from bible_entities.csv  filter '$Type == "ORG"' > {{.out}}
      - task: out
      - echo Legend.ORG - Organization or groups

  occupation:
    cmds:
      - |
        mlr --csv --from bible_entities.csv filter '$Type == "OCCUPATION"'  > {{.out}}
      - task: out

  occupation-summary:
    silent: true
    cmds:
      - |
        # sort by occupation
        echo "top and bottom $(( {{.show_cnt}} / 2)) of sorted by occupation"
        mlr --csv --from bible_entities.csv \
          filter '$Type == "OCCUPATION"' \
            then cut -f Text \
            then count-distinct -f Text \
            then label occupation,count \
            then sort -f occupation > {{.out}}
      - task: out
      - |
        # sort by count
        printf "\n\n\ntop and bottom $(( {{.show_cnt}} / 2)) of sorted by count\n"
        mlr --csv --from bible_entities.csv \
          filter '$Type == "OCCUPATION"' \
            then cut -f Text \
            then count-distinct -f Text \
            then label occupation,count \
            then sort -nf count  > {{.out}}
      - task: out

  gpe:
    silent: true
    cmds:
      - |
        mlr --csv --from bible_entities.csv filter '$Type == "GPE"' > {{.out}}
      - task: out
      - echo Legend.GPE - GeoPoliticalEntity

  norp:
    silent: true
    cmds:
      - |
        mlr --csv --from bible_entities.csv filter '$Type == "NORP"' > {{.out}}
      - task: out
      - echo Legend.NORP - Nationalities Religions or Political Groups

  date-summary:
    cmds:
      - |
        mlr --csv --from bible_entities.csv \
          filter '$Type == "DATE"' \
            then cut -f Text \
            then count-distinct -f Text \
            then head > {{.out}}
      - task: out

  names:
    desc: "Fetch and format output for PERSON=Jesus"
    cmds:
      - |
        mlr --csv --from bible_entities.csv filter '$Type == "PERSON" && $Text == "Jesus"' > {{.out}}
      - task: out

  date:
    silent: true
    desc: "Fetch and format output for DATE=daniel"
    cmds:
      - |
        mlr --csv --from bible_entities.csv \
          filter  '$Type == "DATE" && $Book == "daniel"' > {{.out}}
      - task: out

  out:
    silent: true
    cmds:
      - |
        total=$(mlr --from {{.out}} --csv --headerless-csv-output count)
        printf "Summary:\n   Total: ${total} records\n"
        top=$(({{.show_cnt}} / 2 + 1))
        btm=$(({{.show_cnt}} / 2 ))

        if [ "$total" -le {{.show_cnt}} ]; then
          # For fewer than or equal to {{.show_cnt}} records, display all
          echo "   Showing all $total records"
          cat "{{.out}}" | mlr --c2p --barred cat -n
        else
          # For more than {{.show_cnt}} records, show first ${btm} and last ${btm}
          echo "   Showing {{.show_cnt}} of $total records"
          (head -n${top} "{{.out}}" && tail -n${btm} "{{.out}}") | mlr --c2p --barred cat -n
        fi
