version: 3

tasks:
  default: task -a
  run: task -p generate-json extract

  generate-json:
    cmds:
      - |
        uv run bible.py --generate

  extract-sample:
    cmds:
      - |
        uv run bible.py \
          --extract \
          --bible-json "bible_data.json" \
          --output-json "bible_entities.json" \
          --output-csv "bible_entities.csv" \
          --books john

  extract:
    cmds:
      - |
        uv run bible.py \
          --extract \
          --bible-json "bible_data.json" \
          --output-json "bible_entities.json" \
          --output-csv "bible_entities.csv"

  summary:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          count-distinct -f Type

  org:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "ORG"' \
            then count-distinct -f Text \
            then label ORG_organization_or_groups,Count \
            then head

  occupation:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "OCCUPATION"' \
            then count-distinct -f Text \
            then label occupation,count

  gpe:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "GPE"' \
            then count-distinct -f Text \
            then label GPE_GeoPoliticalEntity,Count \
            then head

  norp:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "NORP"' \
            then count-distinct -f Text \
            then label NORP_Nationalities_Religions_or_Political_Groups,Count \
            then head

  names:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "PERSON"' \
            then count-distinct -f Text \
            then label Names,Count \
            then head

  date:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "DATE" && $Book == "daniel"' \
            then head

  date-summary:
    cmds:
      - |
        mlr --c2p --barred --from bible_entities.csv \
          filter '$Type == "DATE"' \
            then cut -f Text \
            then count-distinct -f Text \
            then head
